---
title: "STUDY PROTOCOL"
subtitle: "Does a data sharing game increase engagement with data sharing training?"
author: "Katie Drax, Kirsty Merret, Robert Thibault, Christopher Warren, and Marcus Munafò"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  word_document:
      number_sections: true
bibliography: rip-protocol.bib
csl: apa.csl
---

# Background

In the UK, funders and publishers are increasingly requiring data sharing as a condition of funding or publication [@2009; @2017;@2020].
Several organisations [@theopenresearchdatataskforce2018; @2021] and individuals, including authors of this study [@munafo2014; @munafo2017], have advocated for the benefits of data sharing, including how this can encourage reuse, and serve as a quality control process that increases the rigour, reproducibility, impact, and efficiency of research 
Despite this support data sharing remains uneven in practice, and is either not done (despite funder and journal requirements) or not done well. 
For example, there is growing evidence that many data deposits on non-curated repositories are not of an adequate standard; deposits do not inlcude a data dictionary, use a proprietary formet, or include potentially identifying information about participants.
Other barriers include researcher attitudes.
For example, researchers may believe that sharing their data will disadvantage them compared to researchers who do not share share their data [@kim2016a]

Therefore, as well as infrastructure (e.g., institutional repositories) and incentives (e.g., recognising data deposits as research outputs), effective data sharing will require training. 
Lack of knowledge about managing and sharing data, including how to do this effectively, is a barrier to both voluntary and mandatory data sharing. However, researchers may not undertake relevant training, perhaps because of a combination of limited time and a lack of awareness of the need for training. 
Educational interventions offer one way to overcoming this barrier. 
Gamified interventions, in particular, could encourage initial engagement with data sharing training. 
However, a recent review of the gamification literature concluded that the effects of gamification are poorly understood, with limited evidence regarding whether gamification does indeed increase engagement [@dichev2017].

The University of Bristol Research Data Service recently created the Researchers, Impact, and Publications (RIP) game [@merrett2020]. 
The creators' initial intention for the game was to use it as a talking point, or icebreaker, with people who were interested in data sharing. 
The game was not designed with a specific theoretical framework or outcome in mind - the creators expected others to use it in whatever way they saw fit.
Adapted from “Cards Against Humanity”, the RIP game aims help people learn about research data management and its relationship to funding and publishing research. 
The Research Data Service are in the process of creating an online version of the card game using Roll20.com.
As of November 2020, the RIP game data had been downloaded at over 150 different locations. 
If shown to be effective in promoting a willingness to engage in data sharing training, the RIP game could form part of a comprehensive approach to increasing the degree and quality of data sharing across the sector.
This study is a randomized controlled trial of the RIP game as an educational intervention to improve attitudes towards, and willingness to engage in, data sharing training.

`r # do we want to keep participant identification forms so we can see if their data sharing increases?`

# Study Objective and Hypotheses

Our primary aim is to evaluate the impact of the RIP game on attitudes towards, and willingness to engage in, data sharing training, compared to the UK Reproducibility Network data sharing primer [@towse2020].

We hypothesise that participants who complete the RIP game will report more positive attitudes towards data sharing training, and be more likely to indicate a willingness to attend a data sharing workshop, than participants in the control condition. `r # isn't this a bit much? do we have the evidence?`

# Study Design

This is a cluster randomized trial - ReproducibiliTea journal clubs will be randomized to complete the [online version of the RIP game](https://app.roll20.net/join/9526650/nPTYBw) as a group, or to read and discuss, the UK Reproducibility Network data sharing primer [@towse2020].
The creators of the RIP game initially designed the game to be delivered with an educator so designing a glossary or concept bank document will help adapt the game for play without an educator.

## Outcome measures

### Engagement questionnaire

This survey from @unal2019 available at https://inlitas.org/survey/index.php/493475?newtest=Y&lang=en looks pretty good let me know if you think we should replicate it.

Q1. 
Training on Open Data helps researchers make their data available to others so that their results can be checked and the data reused for other purposes. 
This training will teach researchers to: produce data which are FAIR: Findable, Accessible, Interoperable, and Reusable; find repositories; use appropriate data formats; manage metadata (information describing datasets); ensure non-identifiability (for researchers working with human data).
Please mark the statements below which you broadly agree with, regarding Open Data. 
You may mark as many as you like.

* I am familiar with this concept
* I am NOT familiar with this concept
* I would find training on this useful
* I already engage with this practice
* I think my organisation already provides sufficient training on this

Q2. We are considering organising a data sharing training session at your organisation. 
If you would like to be invited to this event please provide an email we can send the invitation to below.


### Data sharing measure

To measure data sharing across multiple disciplines, institutions, languages, and countries we will need to measure universal indicators of data sharing. 
There are numerous checklists and guidelines for data management plans and data sharing, but most are designed for specific types of data and few aims to be universal. 
One example of famous universal guidelines are the FAIR principles who claim, “All scholarly digital research objects—from data to analytical pipelines—benefit from application of these principles”. 
Regarding universality, KM and CW suggested the most universal aspect of data sharing will be the data deposit record. 

The record includes:

* Data
* File formats
* License
* Creator(s) names
* Identifier
* Metadata

Our data sharing measure could adapt the FAIR principles, KM and CW’s suggestions, or a combination.
Essentially universal standards about the “content” of shared data will be very difficult to develop. 
Universal standards about the presence of shared data will be easier.

# Study Site

Journal clubs will meet virtually or in-person to play the RIP game, or read and discuss the UKRN primer. 
After their meeting, individual participants in the journal club will each complete the online questionnaire.

# Participants and Recruitment

We will recruit existing ReproducibiliTea journal clubs and randomise them to one of the arms.
ReproducibiliTea is an international journal club  series.
Started at the University of Oxford in 2018 by PhD students, early career researchers in other institutions soon set up their own clubs.
As of 1 June 2021 there are 133 ReproducibiliTea clubs across 25 countries. 
Club structures are not standardised but most are led by early career researchers, meet regularly, are English speaking, and discuss issues related to reproducibility, open research, and research quality (https://reproducibilitea.org/).

We have close relationships with the community, for example KD foundered and led the University of Bristol ReproducibiliTea club and was a member of the ReproducibiliTeam.
The internationality of the group will allow us to recruit people from different countries and contexts and our existing relationships with the clubs, and series as a whole, means we can access them and invite them to participate.
Participants will receive financial reimbursement for their time.

## Inclusion criteria

* 18 years old

## Sample size determination

On 9 April 2021, reproducibilitea.org registered 128 ReproducibiliTea journal clubs across 25 countries.
Some of these clubs may be inactive or uncontactable so we cannot expect to recruit all 128 clubs.
An event organised by the ReproducibiliTeam in November 2020 saw attendees from at least 30 ReproducibiliTea groups suggesting 30 are active and engaged with the ReproducibiliTeam.
Based on this attendance, we will aim to recruit as many clubs as possible but expect around 30 clubs to be interested.

## Withdrawal of participants

We will inform participants that they can withdraw from the study at any time before they begin their engagement quesionnaire.
Only individuals who submit their engagement questionnaire will be reimbursed.

# Randomisation

Cluster randomisation is preferable here to individual randomisation.

# Measures and Materials

The study will require the following materials

* Consent form
* Participant information sheet
* Intervention instructions
* engagement questionnaire

# Procedures

1. Recruit ReproducibiliTea clubs to the study
3. Information sheet sent to ReproducibiliTea club organiser.
We will ask them to distribute the sheet to their members and will answer any questions they have.
4. Randomise the club to one of the three arms, if they agree to participate.
5. Send organiser the instructions for the intervention arm they are randomised to.
4. ReproducibiliTea club holds intervention meeting when convenient
5. ReproducibiliTea members respond to engagement quesionnaire
6. Members reimbursed

# Statistical Plan

`r # xxxx`

# Ethical Considerations and Informed Consent

Ethics approval has will be obtained from the School of Psychological Science Research Ethics Committee at the University of Bristol `r # (Approval Code: )`. 
The study will be conducted according to the revised Declaration of Helsinki (2013) and the 1996 ICH Guidelines for Good Clinical Practice E6(R1). 
The investigator will explain the nature, purpose and risks of the study to the participant. 
We will send the information sheet to the ReproducibiliTea club organiser in advance of the study session and they will distribute it to their members.
There will be no time restriction on how long organisers take to respond, with the exception that organisers who respond after all study places have been filled will not be offered a place on the study. 
Therefore, participants will be given sufficient time to read the information, consider any implications, and raise any questions with the investigators prior to making a decision to participate. 
`r # is this enough for informed consent?`
On [time when this will happen?], participants will be given the opportunity to read the information sheet again and ask the investigator questions. 
Written consent will then be obtained [when should this be done].
Participants will be informed that they are free to withdraw at any time before they begin their engagement questionnaire.

# Safety

There are no expected hazards, due to the study consisting of a meeting and questionnaire of non-vulnerable people that includes no personal or sensitive topics or questions.

# Data Management

All aspects of the General Data Protection Regulation (GDPR) and the Data Protection Act (DPA) 2018 will be adhered to.
Electronic data will be anonymised by a unique numeric identifier. 
Original computer data files will be backed up on a secured University of Bristol network drive.
In accordance with the FAIR (Findable, Accessible, Interoperable, Reusable) principles [@wilkinson2016], and at the end of the study, electronic study data (including finalised data sheet) will be transferred to a designated University of Bristol Research Data Storage Facility (https://data.bris.ac.uk/data/) afor long-term archiving. 
Study data will be kept for a minimum of 15 years. 
At the appropriate time the data sheet will be locked and made open using the University of Bristol Research Data Repository.
Consent forms will be retained by the School of Psychological Science for a period of 10 years after study completion.

## Participant contact details

Participant contact details will be retained for reimbursement. 
They will be destroyed once all participants successfully receive their reimbursement or one year after study completion, whichever comes first.

## Revoked data

Data will be anonymous so we are unable to withdraw data as there is no way to tell which observation belongs to which participant. 

# Quality Control and Quality Assurance

```{r, echo=F}
#* bots
#* satisficing/random responding = low effort, skimming instructions, #skimming questions, guessing answers
```

We will randomise the order of questionnaire items and response options to reduce order effects. 
We will also exclude any responses completed in an implausibly short amount of time on the questionnaire.
Collecting the data using Qualtrics creates the risk of automated form fillers ("bots") and duplicate responses.
We will include at least one compulsory open-ended question and a false question to identify bots.
Post-study checks will allow us to identify duplicate responses and exclude all but the first response.

# Insurance

This study will be sponsored by the University of Bristol. 
The University has Public Liability Insurance to cover the liability of the University to research participants. 
In the event that something goes wrong and a participant is harmed during the research study there are no special compensation arrangements.
If a participant is harmed and this is due to someone's negligence then they may have grounds for a legal action for compensation against Bristol University or one of the other parties to the research, but they may have to pay their own legal costs.

# Publication Policy

The findings from this research study may be published in an appropriate scientific journal (and made available open access), and/or presented at an appropriate meeting.
Study data will be collected and held by the study investigators.
The data will be made available for sharing via a University of Bristol online data repository.

# Study Personnel

Katie Drax

School of Psychological Science

12a Priory Rd

Bristol BS8 1TU

katie.drax@bristol.ac.uk  


Kirsty Merrett

Augustine's Courtyard

Orchard Lane

Bristol BS1 5DS

j.k.merrett@bristol.ac.uk

Marcus Munafò 

School of Psychological Science

12a Priory Road

Bristol, BS8 1TU

marcus.munafo@bristol.ac.uk


Christopher Warren

Augustine's Courtyard

Orchard Lane

Bristol BS1 5DS

Christopher.Warren@bristol.ac.uk


# Contributions and Authorship

KD wrote the first draft of the protocol and is the guarantor of the project.
MM provided feedback and comments for the protocol and will supervise the project.

# Funding Source

This study is supported by the John Climax Benevolent Fund which supports KD’s PhD studentship and provided funds for participant reimbursement.
The funder will have no involvement in any aspects of the study design and conduct.

# Conflicts of Interest

KM and CW are the creators of the RIP game.

# References